# Generated by Django 2.2.3 on 2019-07-26 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190726_1904'),
    ]

    operations = [
        migrations.CreateModel(
            name='bmiCalculate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField(verbose_name='Height(in cm):')),
                ('weight', models.FloatField(verbose_name='Weight(in kg):')),
                ('bmi', models.FloatField()),
                ('date_rec', models.DateField()),
            ],
        ),
    ]
