# Generated by Django 2.2.3 on 2019-07-26 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_bmicalculate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bmicalculate',
            name='date_rec',
            field=models.DateField(verbose_name='Date:'),
        ),
    ]
