# Generated by Django 2.2.3 on 2019-07-26 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190726_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bmicalculate',
            name='bmi',
        ),
    ]
