# Generated by Django 2.2.3 on 2019-07-26 22:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_bmicalculate_bmi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bmicalculate',
            name='date_rec',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Date:'),
        ),
    ]
