# Generated by Django 2.2.3 on 2019-07-26 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190727_0212'),
    ]

    operations = [
        migrations.AddField(
            model_name='bmicalculate',
            name='username',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
    ]
