# Generated by Django 2.2.3 on 2019-08-06 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190802_0357'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='height',
            field=models.FloatField(default=0, verbose_name='Height(in cm):'),
        ),
    ]
