# Generated by Django 2.2.3 on 2019-07-27 23:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bmiCalculate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField(default=0, verbose_name='Height(in cm):')),
                ('weight', models.FloatField(default=0, verbose_name='Weight(in kg):')),
                ('date_rec', models.DateField(default=datetime.datetime.now, verbose_name='Date:')),
                ('calculated_bmi', models.FloatField(default=0.0)),
                ('username', models.CharField(default='SOME STRING', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Event Name')),
                ('event_date', models.DateTimeField(verbose_name='Event Date')),
            ],
        ),
    ]
