# Generated by Django 2.2.3 on 2019-07-28 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_bmrcalculate_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='bmrcalculate',
            name='age',
            field=models.FloatField(default=18.0),
        ),
    ]
