# Generated by Django 2.2.3 on 2019-07-28 15:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190728_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='calorieLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calorie_intake', models.FloatField(default=0, verbose_name='Intake(in kcal): ')),
                ('date_rec', models.DateField(default=datetime.datetime.now, verbose_name='Date:')),
                ('username', models.CharField(default='SOME STRING', max_length=200)),
            ],
        ),
    ]
