# Generated by Django 2.2.3 on 2019-07-28 13:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bmrCalculate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField(default=0, verbose_name='Height(in cm):')),
                ('weight', models.FloatField(default=0, verbose_name='Weight(in kg):')),
                ('date_rec', models.DateField(default=datetime.datetime.now, verbose_name='Date:')),
                ('calculated_bmr', models.FloatField(default=0.0)),
                ('username', models.CharField(default='SOME STRING', max_length=200)),
            ],
        ),
    ]
