# Generated by Django 2.2.3 on 2019-07-28 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_bmrcalculate'),
    ]

    operations = [
        migrations.AddField(
            model_name='bmrcalculate',
            name='sex',
            field=models.CharField(default='SOME STRING', max_length=60),
        ),
    ]
