# Generated by Django 2.2.3 on 2019-07-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_bmrcalculate_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bmrcalculate',
            name='sex',
            field=models.CharField(default='M', max_length=60),
        ),
    ]
