# Generated by Django 2.2.3 on 2019-08-01 23:57

import datetime
from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_calorielog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bmicalculate',
            name='date_rec',
            field=models.DateField(default=datetime.datetime.now, validators=[main.models.clean_date], verbose_name='Date(YYYY-MM-DD):'),
        ),
        migrations.AlterField(
            model_name='bmrcalculate',
            name='date_rec',
            field=models.DateField(default=datetime.datetime.now, validators=[main.models.clean_date], verbose_name='Date(YYYY-MM-DD):'),
        ),
        migrations.AlterField(
            model_name='calorielog',
            name='date_rec',
            field=models.DateField(default=datetime.datetime.now, validators=[main.models.clean_date], verbose_name='Date(YYYY-MM-DD):'),
        ),
    ]
