# Generated by Django 2.2.3 on 2019-08-06 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190802_0357'),
    ]

    operations = [
        migrations.AddField(
            model_name='bmrcalculate',
            name='physicalcalories_burnt',
            field=models.FloatField(default=0.0, verbose_name='Calories Burnt (kcal): '),
        ),
        migrations.AddField(
            model_name='bmrcalculate',
            name='totalcalories_burnt',
            field=models.FloatField(default=0.0),
        ),
    ]
